<a href="https://colab.research.google.com/github/qkrsj/AI-PROGRAMMING/blob/main/week-03/0325pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# DataFrame 생성

from pandas import DataFrame
data = [
    [157000, 39.88, 4.38],
    [51300, 8.52, 1.45],
    [68800, 10.03, 0.87],
    [140000,228.38, 2.16]
]
index = ['NAVER', '삼성전자', 'LG전자', '카카오']
columns = ['종가', 'PER', 'PBR']
df = DataFrame(data=data, index=index,columns=columns)
# print(df)
display(df)

           종가     PER   PBR
NAVER  157000   39.88  4.38
삼성전자    51300    8.52  1.45
LG전자    68800   10.03  0.87
카카오    140000  228.38  2.16

In [ ]:
from pandas import DataFrame
import pandas as pd # Corrected import statement for pandas
FILE_PATH = '/content/' # Define FILE_PATH
filename = '0325.csv'
df = pd.read_csv(FILE_PATH+filename)

print(df.shape)
print(df.columns)
print(df.index)

(5, 4)
Index(['그룹', '인원', '소속', '데뷔년도'], dtype='object')
RangeIndex(start=0, stop=5, step=1)

In [ ]:
# column, index 이름 변경
df.columns = ['group', 'member', 'company', 'year']
# df.index = ['one', 'two', 'three', 'four', 'five']

df

  group  member company  year
0  르세라핌       5    소스뮤직  2022
1   아이브       6     스타쉽  2021
2   뉴진스       5     어도어  2022
3    잇지       5     jyp  2019
4   에스파       4      sm  2020

In [ ]:
# Column data 추출
# 원하는 column들 뽑아서 새로운 data frame에 저장
df_g = df['group']
df_g

# 복수의 column
df_1 = df[['member', 'year']]
df_1

   member  year
0       5  2022
1       6  2021
2       5  2022
3       5  2019
4       4  2020

In [ ]:
# 조건으로 column 데이터 추출

print( df['company'] == 'sm')
print( df['year'] > 2020)
print( (df['member'] >= 5) & df['year'] == 2021)

0    False
1    False
2    False
3    False
4     True
Name: company, dtype: bool
0     True
1     True
2     True
3    False
4    False
Name: year, dtype: bool
0    False
1    False
2    False
3    False
4    False
dtype: bool

In [ ]:
# row data 추출
print(df[1:3])
print(df[:3]) # ex) 1~3번째
print(df[3:])

  group  member company  year
1   아이브       6     스타쉽  2021
2   뉴진스       5     어도어  2022
  group  member company  year
0  르세라핌       5    소스뮤직  2022
1   아이브       6     스타쉽  2021
2   뉴진스       5     어도어  2022
  group  member company  year
3    잇지       5     jyp  2019
4   에스파       4      sm  2020

In [ ]:
# 원하는 row들이 불연속인 경우
# loc, iloc 사용한다 loc는 location, iloc는 index location
df0 = df.loc[[0,2]]
df0

  group  member company  year
0  르세라핌       5    소스뮤직  2022
2   뉴진스       5     어도어  2022

In [ ]:
# 원하는 column, row 데이터 추출
df.colums = [0,1,2,3]
print(df.loc[1:3. :2])
print(df.loc[:.1:3])

  group  member company  year
1   아이브       6     스타쉽  2021
3    잇지       5     jyp  2019
  group  member company  year
0  르세라핌       5    소스뮤직  2022

/tmp/ipykernel_4087/2182129481.py:1: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
  df.colums = [0,1,2,3]

In [ ]:
# Groupby 그룹화 / mean 평균
df0 = df.groupby('member')
df0['year'].mean()

member
4    2020.0
5    2021.0
6    2021.0
Name: year, dtype: float64

In [ ]:
# row 삭제
# drop() 사용
# 복수 삭제시엔 리스트로 한다

print(df)
df = df.drop(df.index[2])
print(df)

  group  member company  year
0  르세라핌       5    소스뮤직  2022
1   아이브       6     스타쉽  2021
2   뉴진스       5     어도어  2022
3    잇지       5     jyp  2019
4   에스파       4      sm  2020
  group  member company  year
0  르세라핌       5    소스뮤직  2022
1   아이브       6     스타쉽  2021
3    잇지       5     jyp  2019
4   에스파       4      sm  2020

In [ ]:
print(df)
df = df.drop(df.index[[1,4]])
print(df)

In [ ]:
# column 삭제
# drop (,axis=1) 사용
print(df)
df = df.drop('member', axis=1)
print(df)

  group  member company  year
0  르세라핌       5    소스뮤직  2022
1   아이브       6     스타쉽  2021
3    잇지       5     jyp  2019
4   에스파       4      sm  2020
  group company  year
0  르세라핌    소스뮤직  2022
1   아이브     스타쉽  2021
3    잇지     jyp  2019
4   에스파      sm  2020

In [ ]:
print(df)
df = df.drop(['member','company'], axis=1)
print(df)